print('hello, world!')
print('quero dormir')
print('amo chocolate')
print('preciso ir a maldivas')
print('eu só me iludo')
print('sonho em ser ator')
print('mereço ser reconhecido')
print('sou talentoso')
print('ainda terei meu valor na globo e netflix')
print('ainda vou me orgulhar muito de mim mesmo')
print('só amo quem não me ama, triste')